import LocalizedStrings from 'react-localization';

export default new LocalizedStrings({
    pt: {
        footer: "Todos os direitos reservados.",
        menu1: "Página Principal",
        menu2: "A Nossa História",
        menu3: "O Pedido",
        menu4: "Gang Madrinhal",
        menu5: "Padrinho",
        menu6: "O Casamento",
        menu7: "Fornecedores",
        menu8: "Viajar Para Sāo Miguel",
        menu9: "Estadia",
        menu10: "Sugestões dos Noivos",
        menu11: "Fotos",
        menu12: "Contactos",
        menu13: "RSVP",
        homeText: "Bem-vindo(s) à página oficial do nosso casamento.",
        brevemente: "Disponível Brevemente!",
        notfound: "Página não encontrada",
        oCasamento1: "O Casamento",
        oCasamento2: "Data",
        oCasamento3: "Hora",
        oCasamento4: "Local",
        contactos1: "Contactos",
        contactos2: "Qualquer dúvida contactem-nos através do email",
        contactos3: "ou enviem-nos uma mensagem para o WhatsApp (número inglês; os número portugueses não estão activos) ou Messenger.",
        fotos1: "Secção disponível após o casamento!",
        viajar1: "Lisboa",
    },
    en: {
        footer: "All rights reserved.",
        menu1: "Home",
        menu2: "Our Story",
        menu3: "The Proposal",
        menu4: "Bridal Gang",
        menu5: "Best Man",
        menu6: "The Wedding",
        menu7: "Suppliers",
        menu8: "Travelling to Sāo Miguel",
        menu9: "Accommodation",
        menu10: "Suggestions",
        menu11: "Photos",
        menu12: "Contacts",
        menu13: "RSVP",
        homeText: "Welcome to our wedding's official web site.",
        brevemente: "Page available soon.",
        notfound: "Page not found",
        oCasamento1: "The Wedding",
        oCasamento2: "Date",
        oCasamento3: "Time",
        oCasamento4: "Location",
        contactos1: "Contacts",
        contactos2: "If you have any questions just send an email to",
        contactos3: "or send us a message on WhatsApp or Messenger.",
        fotos1: "Available after the wedding!",
        viajar1: "Lisbon",
    }
});