import LocalizedStrings from 'react-localization';

export default new LocalizedStrings({
    pt: {
        ou: "ou",
        DIA: "DIA",
        footer: "Todos os direitos reservados.",
        menu1: "Página Principal",
        menu2: "A Nossa História",
        menu3: "O Pedido",
        menu4: "Gang Madrinhal",
        menu5: "Padrinho",
        menu6: "O Casamento",
        menu7: "Fornecedores",
        menu8: "Viajar Para Sāo Miguel",
        menu9: "Estadia",
        menu10: "Sugestões dos Noivos",
        menu11: "Fotos",
        menu12: "Contactos",
        menu13: "RSVP",
        homeText: "Bem-vindo(s) à página oficial do nosso casamento.",
        brevemente: "Disponível Brevemente!",
        notfound: "Página não encontrada",
        oCasamento1: "O Casamento",
        oCasamento2: "Data",
        oCasamento3: "Hora",
        oCasamento4: "Local",
        contactos1: "Contactos",
        contactos2: "Qualquer dúvida contactem-nos através do email",
        contactos3: "ou enviem-nos uma mensagem para o WhatsApp (número inglês; os número portugueses não estão activos) ou Messenger.",
        fotos1: "Secção disponível após o casamento!",
        viajar1: "Lisboa",
        estadia1: "Estadia",
        estadia2: "Neste momento há muita oferta de estadia em São Miguel. Se vêm de férias por alguns dias recomendamos um airbnb ou hostel no centro de Ponta Delgada, mas se quiserem ficar connosco no local do casamento, por favor vejam a informação abaixo relativa ao Convento de São Francisco. Deixamos outras sugestões abaixo, mas apelamos ao vosso sentido crítico pois como podem imaginar nós não costumamos alugar espaço para ficarmos.",
        estadia3: "local do casamento",
        estadia4: "Enviar email para",
        estadia5: "para marcações com 10% de desconto relativamente ao preço no",
        estadia6: "Nunca ficámos neste hotel, mas já lá jantámos 2x (noite de sushi) e visitámos o espaço. O staff é super simpático e o jardim é fantástico. Recomendamos darem uma vista de olhos.",
        estadia7: "Qualquer dúvida em que possamos ajudar ou dar uma opinião falem connosco.",
        estadia8: "Independentemente de onde fiquem, recomendamos alugar carro (a nosso ver é mesmo obrigatório para poderem ver a ilha). Algumas sugestões (baseadas em críticas no Google), mas novamente apelando ao vosso sentido crítico porque não costumamos alugar carro na ilha:",
        pedido1: "O Pedido",
        pedido2: "Data: 3 de Março de 2017",
        pedido3: "Local: Praia do Pópulo, São Miguel (Açores)",
        pedido4: "Foi no ano de 2006 (a 29 de Julho de 2006 mais precisamente), primeiro ano de namoro, que o João fez um piquenique na praia para a Isabel (infelizmente não há fotos desse evento). Essa surpresa contou com cúmplices, os pais do João, que vendaram e levaram a Isabel ao local, que não fazia ideia do que a esperava. Apesar do esforço do João, nesse dia ele não teve muita sorte (não fosse o João) porque teve que acarinhar uma Isabel com febre (a Isabel tem frequentemente uma pontaria enorme em ficar doente em alturas muito pouco convenientes).",
        pedido5: "Em 2017 o João resolveu repetir a surpresa, desta feita para aproveitar a fazer o pedido de casamento. Obviamente que a Isabel suspeitou, mas 1) já tinham surgido outras oportunidades, 2) o João estava super calmo, e 3) passou-se praticamente 1h até que o João resolveu fazer magia. E ainda conseguiu enganar a Isabel a levantar-se para se poder ajoelhar e pedir a Isabel em casamento. \"Queres continuar a fazer-me o homem mais feliz do mundo?\".  Foi muito bonito. Houve uma pequena lágrima (da Isabel. claro), beijo, abraço e muitos sorrisos. E, claro, algumas fotos. Por isso aqui fica. Esperemos que tenham gostado de partilhar um pouco do momento connosco. :)",
        fornecedores1: "Fornecedores",
        fornecedores2: "Espaço",
        fornecedores3: "Fotografia",
        fornecedores4: "Noiva",
        fornecedores5: "Noivo",
        fornecedoresBrevemente: "Informaçāo brevemente disponível!",
        historia1: "A Nossa História",
        historia2: "Amiga, gentil, cheia de amor para dar. A “emotiva” da relação. Cientista. Adora o que faz, o que a torna por vezes demasiado viciada no trabalho, mas também adora yoga, fotografia e dança. Adora a sua família e os seus amigos, vê o melhor nas pessoas. Preocupada, ansiosa e por vezes “stressadinha”, anda a aprender a ser ela própria e a aceitar as coisas como elas são.",
        historia3: "Meigo, sensato, ponderado. O “racional” da relação. Programador. Trabalhador e aplicado. Por vezes demasiado relaxado, podendo parecer um pouco desligado, mas é muito amigo dos seus amigos e de qualquer pessoa, tendo bom querer para toda a gente. Se possa parecer tímido em certas circunstâncias, quando ganha à vontade consegue ser super divertido. Com uma cultura bem acima da média (altamente impulsionada pela sua facilidade em navegar na internet), adora música e tecnologia.",
        historia4: "Fazemos bem um ou outro, tornamo-nos melhores quando estamos juntos.",
        historia5: "Ambos adoramos ir a festivais de música. E ambos adoramos jogos de computador - um fim de semana perfeito por vezes é passado na “ronha” no sofá, juntos, a jogar, ou a ver séries.",
        historia6: "Ambos adoramos viajar, especialmente juntos.",
        historia7: "Gostamos de rir e de nos divertir um com o outro. Por isso para fazer o que quer que seja, desde viajar, a festival de música, a coisas banais como ir às compras – bastamos um ao outro, e podemos sempre contar um com o outro.",
        historia8: "Somos ambos de Ponta Delgada, ambos nascidos no Hospital de São José. O João viveu toda a sua infância em São Miguel, até aos 18 anos. A Isabel viveu em dos 0 aos 2 anos em São Miguel com os pais, dos 2 aos 9 anos em Santa Maria com os avós maternos, voltou a São Miguel dos 9 aos 15 anos para viver com o pai, e aos 15 anos foi viver para Leça da Palmeira (Porto).",
        historia9: "Conhecemo-nos em 2005 no festival Maré de Agosto, na ilha de Santa Maria. Apesar de que o João diz que se sentiu logo atraído pela Isabel, ela não lhe liguou nenhuma – achou que era mais um menino bonito “com a mania”. Não podia estar mais errada...",
        historia10: "No início de 2006 o João mandou uma mensagem à Isabel pelo Hi5 (quem ainda se lembra do Hi5???), que levou a que trocássemos contactos e começássemos a falar via MSN Messenger e posteriormente telemóvel. Quando nos vimos pessoalmente novamente aconteceu tudo naturalmente, e rapidamente virou oficial – a 11 de Abril de 2006. A Isabel tinha acabado de fazer 18 anos e o João caminhava para os 17 anos.",
        historia11: "Entretanto a Isabel entrou na universidade (Setembro de 2006), no curso de Análises Clínicas e Saúde Pública, na Escola Superior de Tecnologias da Saúde do Porto (ESTSP), mas o João ainda tinha mais um ano de secundário pela frente, pelo que durante 1 ano e meio namorámos à distância – a Isabel em Leça da Palmeira e o João em São Miguel.",
        historia12: "Em 2007 o João mudou-se para o Porto para ingressar na universidade, mais concretamente para estudar Engenharia Informática no Instituto Superior de Engenharia do Porto (ISEP).",
        historia13: "No início de 2010 estivemos novamente longe um do outro por 3 meses (enquanto a Isabel esteve na Finlândia como estudante ERASMUS), mas o João foi visitar.",
        historia14: "No Verão de 2010 a Isabel terminou a primeira licenciatura, mas não quis ficar por aí e em Setembro foi para Braga para estudar Biologia Aplicada na Universidade do Minho. Em 2012 o João terminou o curso e mudou-se para Braga, onde vivemos juntos pela primeira vez (com amigas), mas foi em 2013 que fomos viver só os 2 (mais a Sacha! A gata da Isabel), após o João ter arranjado o seu primeiro trabalho como programador.",
        historia15: "Em 2014 o João teve uma oferta para vir para Exeter (Reino Unido) trabalhar, e mais uma vez estivemos 1 ano e meio separados – o João em Exeter e a Isabel em Braga. Mais uma vez, víamo-nos fisicamente de 3 em 3 meses.",
        historia16: "Em 2015 a Isabel terminou o mestrado em Ciências da Saúde (Neurociências) e juntou-se ao João em Exeter para fazer o doutoramento (Estudos Médicos – estudos de genético na doença de Alzheimer), onde vivemos desde então.",
        historia17: "Em 2017 o Deago (lê-se Diego, mas quem originalmente lhe deu o nome claramente falhou) juntou-se à nossa pequena família (agora somos 3!).",
        historia18: "Em 2017 o João pediu a Isabel em casamento e a 11 de Maio de 2019.",
        historia19: "Ainda não sabemos exactamente para onde vamos a seguir. Temos planos e ambições, mas muito poderá mudar. Tem sido uma aventura gira, em que temos crescido e amadurecido juntos.",
        historia20: "Ao longo dos anos tivemos os nossos problemas, claro (estranho seria se não tivessemos!), mas somos uns apaixonados um pelo outro, e vemo-nos a continuar a construir a nossa história, a construir família, e a envelhecer juntos.",
        historia21: "13 anos depois de estarmos juntos, vamos finalmente casar!",
        sugestoes1: "Sugestões dos Noivos",
        sugestoes2: "Estamos a planear fazer um pequeno programa para a Quarta-Feira e Quinta-Feira (8 e 9 de Maio) antes do casamento para fazermos algo por São Miguel com os convidados se queiram juntar a nós. O que estamos a pensar neste momento seria um dos dias por Ponta Delgada, que poderia incluir um passeio de barco (Whale Watching, por exemplo), e o outro dia nas Furnas (cozido das Furnas, bolos lêvedos, Poça da Dona Beija). Os custos seriam assegurados individualmente, como poderão compreender.",
        sugestoes3: "Mais detalhes em breve.",
        sugestoes4: "À parte desses 2 dias, vejam as nossas sugestões gerais abaixo, que temos construído ao longo dos anos e com contribuição de amigos.",
        sugestoes5: "3 aplicações essenciais:",
        sugestoes6: "Onde é possível ver, em tempo real, através de câmaras, como está o tempo em todas as partes da ilha, o que é óptimo porque isso permite definir a zona para onde ir diariamente;",
        sugestoes7: "Ver diariamente/várias vezes ao dia;",
        sugestoes8: "Consegue-se ver do telemóvel;",
        sugestoes9: "Infelizmente agora tem publicidade, mas basta fechar.",
        sugestoes10: "Trilhos",
        sugestoes11: "Para visitar a Ponta da Ferraria, e saber as marés para poder entrar na água.",
        sugestoes12: "Na mala:",
        sugestoes13: "Fatos de banho / biquínis (um, pelo menos, mais velho para algumas águas que mancham e alargam os elásticos pelas temperaturas altas, como no Parque Terra Nostra, na Poça Dona Beija e na Caldeira Velha)",
        sugestoes14: "Toalhas de cor escura – mesma razão de cima",
        sugestoes15: "Botas / sapatilhas para caminhada",
        sugestoes16: "Protector solar e chapéu",
        sugestoes17: "Impermeável - No geral estar preparado/a que no mesmo dia pode tanto fazer sol num momento, como chover no minuto a seguir (De manhã pode estar um dia de verão e de tarde uma tempestade!!)",
        sugestoes18: "Sapatos / sandálias de plástico para o fundo do ilhéu",
        sugestoes19: "Espaço na mala para levar comida da boa!",
        sugestoes20: "Sugestões de dias (ser flexível em alterar a ordem dos dias é essencial, convém aproveitar as zonas que estão boas para visitar de acordo com as câmaras – particular atenção para a Lagoa do Fogo e as 7 cidades que estão frequentemente encobertas / com nevoeiro e que valem a pena quando o céu está limpo!):",
        sugestoes21: "(e outras coisas para outros dias, nomeadamente restaurantes)",
        sugestoes22: "Avenida (Passeio ao longo da avenida)",
        sugestoes23: "Portas do Mar / marina",
        sugestoes24: "Portas da cidade",
        sugestoes25: "Câmara Municipal",
        sugestoes26: "Matriz",
        sugestoes27: "Mercado da Graça",
        sugestoes28: "(a sopa de peixe é muito boa; tem nova gerência)",
        sugestoes29: "A noiva pessoalmente é fã do restaurante",
        sugestoes30: "A tarte de inhame é muito boa. Para almoçar/jantar só com reserva (está sempre cheio!). Pelos vistos também é fixe para um chá ou café, mas nunca lá fomos senão para refeição.",
        sugestoes31: "Miradouro Pico do Carvão",
        sugestoes32: "Lagoa das Empadadas",
        sugestoes33: "Lagoa do Canário",
        sugestoes34: "Mata do Canário",
        sugestoes35: "Miradouro da Boca do Inferno",
        sugestoes36: "Miradouro Vista do Rei, que tem vista sobre a Lagoa das Sete Cidades. Uma das lagoas é azul e outra verde e é possível notar claramente esse contraste",
        sugestoes37: "Ao lado do Miradouro há um hotel abandonado, o Hotel Monte Palace (não tenho a certeza se já está em obras, mas está a ser reconstruído)",
        sugestoes38: "Descida para a Lagoa das Sete Cidades de carro, parar o carro e contornar a lagoa azul (a maior) a pé. Se houver merenda, fazer um piquenique na beira da lagoa",
        sugestoes39: "Mosteiros, onde há piscinas naturais. O mar tem partes com um azul incrível que contrasta com o preto das rochas e branco da espuma das ondas",
        sugestoes40: "Termas da Ferraria, um SPA Termal com várias piscinas – uma delas ao ar livre, em cima do mar - jacuzzi, massagens, banho turco… Dá para tomar banho no mar, mas tem que se ver na app qual é a melhor altura (há uma termal que sai no mar e se a maré está muito baixa fica demasiado quente, se a maré está muito alta não se sente e é frio)",
        sugestoes41: "(Se estiver muito nevoeiro, mais vale deixar para outro dia porque não se vê nada)",
        sugestoes42: "Miradouro da Serra da Barrosa, que fica no conselho de Vila Franca do Campo",
        sugestoes43: "Descer a pé para a Lagoa do Fogo (2 km até à lagoa), por um trilho considerado difícil, cerca de 1 hora ir e vir, mas vale a pena",
        sugestoes44: "Depois, descer de carro para a Caldeira Velha, 5 Km para baixo (pelo caminho encontram-se vários outros miradouros)",
        sugestoes45: "A Caldeira Velha (entrada 2€ para adultos, 4€ para famílias e 1€ para crianças) é um monumento natural que faz parte da Reserva da Biosfera. Tem imensa vegetação exótica, uma poça de água quente e uma cascata também quente para banhos termais (castanhas, devido ao ferro). É um cenário que poderia ser paradisíaco, mas é pouco selvagem e com muita gente. A Caldeira está localizada na cratera do Vulcão do Fogo, tem fumarolas e uma nascente de água termal. Tem chuveiros de água fria e vestiários, para quem quiser experimentar as poças",
        sugestoes46: "Praia de Santa Bárbara;",
        sugestoes47: "Fábrica de Licores Mulher do Capote",
        sugestoes48: "Fábrica de Chá de Porto Formoso ou Gorreana (ainda só conseguimos ir à da Gorreana)",
        sugestoes49: "Trilho do Salto do Prego (4,5 Km). Demora cerca de 2h00, a meio tem uma cascata linda – mas fria – onde é possível tomar banho. Termina na Aldeia do Sanguinho, uma aldeia em (re)construção que parece saída de um conto de fadas",
        sugestoes50: "Restaurante",
        sugestoes51: "Miradouro do Castelo na Ribeira Grande",
        sugestoes52: "Poços de São Vicente Ferreira - excelentes para tomar banho num dia bonito",
        sugestoes53: "Ir de carro ao Miradouro do Pico do Ferro com vistas sobre a Lagoa das Furnas",
        sugestoes54: "Ir de carro pela costa sul para a Lagoa das Furnas e parar o carro no lado das fumarolas – 0,50€ – para fazer o trilho à volta da lagoa, que demora cerca de 2h00 / 2h30",
        sugestoes55: "No lado sul da lagoa, a meio do trilho, a rodear a Ermida de Nossa Senhora das Vitórias, aparece a Mata Jardim José do Canto (a visita custa 2€)",
        sugestoes56: "Pelas 12h30 vale a pena estar novamente nas fumarolas para ver tirar o cozido. As panelas são colocadas pelas 6h da manhã nas caldeiras, pelos restaurantes e particulares, e ficam a cozinhar até ao meio dia. Qualquer pessoa pode cozinhar aqui, desde que leve, claro, a panela com o cozido de casa. O custo para cozinhar nas caldeiras são 3€. A caldeira tem de ser fechada com uma tampa de madeira, coberta com terra e não pode ser aberta até o cozido estar pronto",
        sugestoes57: "Para almoçar o cozido recomendamos os restaurantes Tony´s ou Miroma",
        sugestoes58: "Poça da Dona Beija",
        sugestoes59: "3€ a entrada, água a 38-40ºC. A água está carregada de minerais essenciais. Balneários disponíveis, com água quente e fria",
        sugestoes60: "Parque Terra Nostra (o bilhete custa 6€). Logo à entrada tem um tanque de água termal onde se pode tomar banho. A água é quente e alaranjada (não se vê o fundo) e está a 35 / 40 graus, o provoca uma sensação de relaxamento maravilhosa. A água está carregada de minerais essenciais. Existem outras duas piscinas pequenas e o parque tem balneários disponíveis",
        sugestoes61: "Passar pelo Miradouro Salto do Cavalo, a 760 metros de altitude, onde se vê uma vasta vista sobre o vale da Povoação e as suas sete lombas. Ao fundo, até ao horizonte, surge o mar",
        sugestoes62: "Ir até à Praia da Ribeira Quente, onde a existência de nascentes hidrotermais submarinas tornam a água do mar quente<",
        sugestoes63: "Regressar pela costa norte",
        sugestoes64: "Ilhéu de Vila Franca",
        sugestoes65: "agora aparentemente pode-se comprar os bilhetes online, anteriormente tínhamos que ir super cedo para lá porque só vendem 400 bilhetes por dia. Podem ir passar a manhã ou a tarde no ilhéu. Em maré baixa tem uma praia pequenita, senão ficam nas zonas de rocha. Tomar banho no ilhéu é uma experiência muito gira. Recomendamos levar sapatos de plástico para andar nas rochas já que o fundo do ilhéu é rocha e pode ser desconfortável",
        sugestoes66: "Fábrica do Morgado – queijadas da Vila Franca",
        sugestoes67: "Praias de Água d’Alto",
        sugestoes68: "Cascata do Segredo",
        sugestoes69: "Miradouro do Pisão",
        sugestoes70: "Caloura e praia da Caloura (come-se bem no",
        sugestoes71: "Outras sugestões",
        sugestoes72: "A costa Norte por norma é sempre mais bonita que a costa Sul (miradouros, viagem, etc.), por isso se estiver um dia bonito aconselhamos dar prioridade",
        sugestoes73: "(recomendamos o absurdo - cerveja e camarões, e o gelado de canela)",
        sugestoes74: "(tomar um copo)",
        sugestoes75: "(come-se muito bem e não é caro)",
        sugestoes76: "Estufas de Ananás",
        sugestoes77: "(o que vale a pena são as saladas e os gelados! Os crepes também são bons)",
        sugestoes78: "Restaurante o Galego",
        sugestoes79: "(o melhor bife)",
        sugestoes80: "Restaurante da Associação Agrícola",
        sugestoes81: "(sinceramente nunca lá fomos, mas tem muita reputação)",
    },
    en: {
        ou: "or",
        DIA: "DAY",
        footer: "All rights reserved.",
        menu1: "Home",
        menu2: "Our Story",
        menu3: "The Proposal",
        menu4: "Bridal Gang",
        menu5: "Best Man",
        menu6: "The Wedding",
        menu7: "Suppliers",
        menu8: "Travelling to Sāo Miguel",
        menu9: "Accommodation",
        menu10: "Suggestions",
        menu11: "Photos",
        menu12: "Contacts",
        menu13: "RSVP",
        homeText: "Welcome to our wedding's official web site.",
        brevemente: "Page available soon.",
        notfound: "Page not found",
        oCasamento1: "The Wedding",
        oCasamento2: "Date",
        oCasamento3: "Time",
        oCasamento4: "Location",
        contactos1: "Contacts",
        contactos2: "If you have any questions just send an email to",
        contactos3: "or send us a message on WhatsApp or Messenger.",
        fotos1: "Available after the wedding!",
        viajar1: "Lisbon",
        estadia1: "Accommodation",
        estadia2: "At the moment there is a lot of offering in Sāo Miguel island. If you are taking a few days of holidays, we recommend booking an AirBNB or hostel in the centre of Ponta Delgada, although if you are looking to stay closer to the wedding venue please see the below details regarding the venue. We will also add a few suggestions below, but bear in mind we don't usually book any of these places ourselves.",
        estadia3: "wedding venue",
        estadia4: "Send an email to",
        estadia5: "for 10% discount in bookings compared to the price at",
        estadia6: "We have never booked this hotel, but have had a sushi dinner and visited the venue. Staff is very polite and the garden is fantastic. We recommend having a look at this one.",
        estadia7: "For any questions, opinions or anything else we could help with please contact us.",
        estadia8: "Regardless of where you will stay we definitely recommend renting a car (in our opinion it is pretty much mandatory to be able to see the island properly). Some suggestions based on a quick Google search, but again make sure to do a bit of your own research because we do not typically rent a car in the island:",
        pedido1: "The Proposal",
        pedido2: "Date: March 3rd 2017",
        pedido3: "Location: Pópulo beach, São Miguel (Azores)",
        pedido4: "In the year of 2006 (more specifically July 29th 2006), during the first year of being a couple, João planned a picnic at the beach for Isabel (Unfortunately there are no pictures of this event). This surprise had a few accomplices, namely João's parents, who blindfolded and took Isabel (who had no idea what was waiting for her) to the location. Unfortunately even with all of João's effort, he wasn't very lucky on that day (typical João) because he had to cuddle with a feverish Isabel (she is prone to becoming ill at the most convenient of times).",
        pedido5: "In 2017 João decided to repeat the surprise, but this time to actually propose. Obviously Isabel suspected but 1) there were a few other opportunities, 2) João was way too calm, e 3) one hour passed until João decided to do his magic. He was still able to trick Isabel into standing so he could kneel down to propose. \"Will you make me the happiest man in the world?\". It was very touching. A small tear fell (obviously Isabel's), kiss, hugs and plenty of smiles. And obviously some photos taken. And that is it. We hope you enjoyed this little story we shared with you. :)",
        fornecedores1: "Suppliers",
        fornecedores2: "Venue",
        fornecedores3: "Photography",
        fornecedores4: "Bride",
        fornecedores5: "Groom",
        fornecedoresBrevemente: "Information available soon!",
        historia1: "Our Story",
        historia2: "Friendly, gentle and filled with love to give. The \"emotional\" one in the relationship. Is a scientist and loves her work, which sometimes can turn her into a workaholic. Also loves yoga, photography and dancing. Loves her family and friends and tries to see the best in people. Worried, anxious and sometimes a \"nagger\", has been learning to be herself and to accept things the way they are.",
        historia3: "Tender, sensible and thoughtful. The \"pragmatic\" one in the relationship. Is a programmer and works hard and can apply himself to it. Sometimes might be a bit too relaxed and might appear distant, but is a real friend for anyone with a good heart for everyone. He might seem shy under some circumstances but as soon as he is comfortable he can be very fun. With a general knowledge well above average (very much thanks to his ease in navigating the Internet), loves music and technology.",
        historia4: "We are good for each other and are better people when we are together.",
        historia5: "We both love going to music festivals. Also love video games and sometimes the perfect weekend for us is spent just lounging on the sofa together watching TV shows or playing video games.",
        historia6: "Both love travelling, particularly together.",
        historia7: "We like to laugh and have fun with each other. So for things like travelling or going to a music festival or even trivial things like going grocery shopping - all we need is each other, and we can definitely count on that.",
        historia8: "Both born in Ponta Delgada, at the Sāo José hospital. Joāo lived in Sāo Miguel throughout his childhood up until he turned 18. Isabel lived from 0 to 2 years old in Sāo Miguel with her parents, and then 2 to 9 years old in the island of Santa Maria with her maternal grandparents, went back to Sāo Miguel between 9 and 15 years old to live with her father, and finally at 15 she went to live in Leça da Palmeira (Porto).",
        historia9: "We met in 2005 at the festival Maré de Agosto that occurs in the island of Santa Maria. Even though Joāo says he felt some attraction for Isabel, she didn't seem to care for him much back then - thinking he was just a cocky \"pretty boy\". She could not have been more mistaken...",
        historia10: "At the beginning of 2006 Joāo sent Isabel a message through Hi5 (remember Hi5??), which lead to a contact exchange and starting to chat on both MSN Messenger and mobile phone. The first time we personally met everything happened very naturally and became official quickly - on 11th April 2006. Isabel just turned 18 years old and Joāo was almost 17.",
        historia11: "Meanwhile in September 2006 Isabel enrolled into university, in the degree of Análises Clínicas e Saúde Pública at the Institute of Health Sciences in the Polytechnic of Porto (ESTSP), while Joāo was on his last year of high school, which means that we were a long distance couple for a year - Isabel in Porto and Joāo in Sāo Miguel.",
        historia12: "In 2007 Joāo moved to Porto in order to enroll in university, specifically to study Computer Engineer at the Engineering Insitute in the Polytechnic of Porto (ISEP).",
        historia13: "During the beginning of 2010 we again temporarily became a long distance couple for 3 months while Isabel was doing an exchange student program called ERASMUS in Finland. Although Joāo visited her once.",
        historia14: "Isabel finished her first degree during the summer of 2010, but she decided that she wanted more so in September she moved to the city of Braga to study Applied Biology at the University of Minho. In 2012 Joāo moved to Braga as well, where we lived together for the first time (with a few roommates). In 2013 we moved into our own apartment (along with Isabel's cat named Sacha) after Joāo found his first job as a programmer.",
        historia15: "In 2014 Joāo was offered to work in Exeter (United Kingdom), and once again we were a long distance couple for a year and a half - Joāo living in Exeter and Isabel living in Braga. We would still see each other every 3 months.",
        historia16: "After finishing her Master's Degree in Health Sciences (Neuroscience) Isabel finally moved with Joāo in Exeter to enroll in a PhD (Medical studies, genetic research of Alzheimer's disease), where we have been living since. ",
        historia17: "In 2017 we welcomed a new family member in the form of a cat named Deago (reads similar to Diego, but whoever named him wanted to be fancy) and now there are 3 of us in this small family.",
        historia18: "Joāo asked Isabel to marry him in 2017.",
        historia19: "We still do not know where we are going next but we have our own goals and plans, but many things can change in the meantime. It has been a great adventure and we have grown and matured a lot throughout.",
        historia20: "Over the years we have had our own arguments and fights (it would be weird if we hadn't!), but we are in love with each other and can see ourselves continuing to build a story and a family, and even growing old together.",
        historia21: "13 years later we are finally getting married!",
        sugestoes1: "Bride and Groom's Suggestions",
        sugestoes2: "We are planning on creating a short program for Wednesday and Thursday (8th and 9th of May) before the wedding to do several things around the island with guests who would like to join us. At the moment we are thinking of spending one of the days in Ponta Degada which could include going on a boat (for example Whale Watching) and another day in Furnas (Furnas stew, bolos lêvedos, Dona Beija pool). Any costs would be up to the individual as you should understand.",
        sugestoes3: "More details available soon.",
        sugestoes4: "Aside fom those 2 days, we will give you some suggestions that we have built over the years with many friends' contributions below.",
        sugestoes5: "3 essential Apps:",
        sugestoes6: "Where you can access webcams in real time to check on the weather in different parts of the island. This allows us to decide where to go on a specific day or time;",
        sugestoes7: "Check daily or several times per day;",
        sugestoes8: "Can be accessed from a mobile phone;",
        sugestoes9: "Unfortunately they are now using ads, but simply close them if they pop up.",
        sugestoes10: "Trails and Hiking",
        sugestoes11: "When visiting Ponta da Ferraria to check on the tides and how warm the water would be.",
        sugestoes12: "In the travel bag:",
        sugestoes13: "Swimwear (at least an older or cheaper set due to the possibility of some of the waters damaging them, such as in Terra Nostra Park, Dona Beija pool or Caldeira Velha pool)",
        sugestoes14: "Dark coloured towels - for the reasons stated above",
        sugestoes15: "Hiking boots / trainers",
        sugestoes16: "Sun screen and hat",
        sugestoes17: "Raincoat - In general be ready for it to be sunny and suddenly rain in the space of minutes (You can have a summer day and a few hours later it feels like you're in the middle of a storm!)",
        sugestoes18: "Plastic shoes / slippers to walk on rocky places near the coast or the islet",
        sugestoes19: "Room in your bag to bring home amazing food!",
        sugestoes20: "Day suggestions (this list is not in a specific order, you should be flexible and take advantage of certain areas of the island with good weather according to the webcams - be particularly mindful of Fogo and Sete Cidades lagoons as they are frequently covered in fog and are very much worth it when the sky is clear!)",
        sugestoes21: "(other essentials you might need)",
        sugestoes22: "Avenue (Walking along the avenue)",
        sugestoes23: "Doors to the Sea (Portas do Mar) and quay",
        sugestoes24: "Doors to the City (Portas da Cidade)",
        sugestoes25: "Town Hall",
        sugestoes26: "Central Church",
        sugestoes27: "Graça Market (Mercado da Graça)",
        sugestoes28: "(the fish soup is amazing; has recently changed owners)",
        sugestoes29: "The bride is personally a fan of the restaurant",
        sugestoes30: "The yam pie is very good. You will need to book in advance for lunch or dinner as it is constantly fully booked! Also pleasant for tea or coffee, but we have personally never been to outside of meal times.",
        sugestoes31: "Pico do Carvão Viewpoint",
        sugestoes32: "Empadadas Lagoons",
        sugestoes33: "Canário Lagoon",
        sugestoes34: "Canário Forest",
        sugestoes35: "Boca do Inferno Viewpoint",
        sugestoes36: "King's Viewpoint (Miradouro Vista do Rei), overlooks the Sete Cidades Lagoons. One of them is blue and the other is green and you can clearly see the contrast here",
        sugestoes37: "Next to the Viewpoint is an abandoned hotel, the Monte Palace Hotel (we are not sure if it is still undergoing construction, but the plan is to re-build it)",
        sugestoes38: "Descent to Sete Cidades Lagoon by car, park somewhere and go around the blue lagoon (larger) by foot. If you have any snacks, by the lagoon is a very good place to picnic (please clean up afterwards)",
        sugestoes39: "You can go to Mosteiros where there are sea water pools. In some places you can see how much contrast you get from the blue of the sea with the black of the rocks",
        sugestoes40: "Ferrarias Spa, a Thermal Spa with several pools - one of them is outdoor right next to the sea - jacuzzi, massages, Turkish bath... You can swim in the sea, but you should check the App for the best times of day temperature-wise",
        sugestoes41: "(If the day is too foggy, you are better off doing this in a different day)",
        sugestoes42: "Serra da Barrosa Viewpoint, in the county of Vila Franca do Campo",
        sugestoes43: "Go down to the Fire Lagoon (Lagoa do Fogo) 2 km up until the water itself on a trail that some consider challenging. It totals about 1 hour each way, but it is worth it",
        sugestoes44: "Aftewards go down to Caldeira Velha by car for another 5 km (there are several viewpoints along the way)",
        sugestoes45: "Caldeira Velha (2€ entrance fee for adults, 4€ for families and 1€ for children) is a natural monument that is part of the Biosphere Reserve. It has a lot of exotic vegetation, a warm water pool and a warm water waterfall for thermal bathing (brown water is due to the iron content). It could have been like being in paradise, but it has too many people making a ruckus. The Caldeira is located in the Fire Volcano's crater, you will find fumeroles and a thermal water spring. There are ameneties that provide cold water showers and changing rooms to whoever wants to try the pools",
        sugestoes46: "Santa Bárbara beach;",
        sugestoes47: "Liqueur Factory Mulher do Capote",
        sugestoes48: "Tea Factory of Porto Formoso or Gorreana (we have only been to Gorreana yet)",
        sugestoes49: "Salto do Prego Trail (4.5 km). It 2 hours on average to do it, and you will find a gorgeous waterfall in the middle of the trail, where you can enjoy an extremely cold bath. It ends in the village of Sanguinho, which is under (re)construction and looks like a scene from a fairy tale",
        sugestoes50: "Restaurant",
        sugestoes51: "Ribeira Grande Castle's Viewpoint",
        sugestoes52: "Sāo Vicente Pools - excelent for a swim in a gorgeous day",
        sugestoes53: "Drive to the Ferro Mountain (Pico do Ferro) with views above the Furnas Lagoon",
        sugestoes54: "Drive around the southern coast to Furnas lagoon and park near the fumeroles - 0,50€ fee - and walk the trail that goes around the lagoon, takes on average 2 to 2 and a half hours.",
        sugestoes55: "No lado sul da lagoa, a meio do trilho, a rodear a Ermida de Nossa Senhora das Vitórias, aparece a Mata Jardim José do Canto (a visita custa 2€)",
        sugestoes56: "Pelas 12h30 vale a pena estar novamente nas fumarolas para ver tirar o cozido. As panelas são colocadas pelas 6h da manhã nas caldeiras, pelos restaurantes e particulares, e ficam a cozinhar até ao meio dia. Qualquer pessoa pode cozinhar aqui, desde que leve, claro, a panela com o cozido de casa. O custo para cozinhar nas caldeiras são 3€. A caldeira tem de ser fechada com uma tampa de madeira, coberta com terra e não pode ser aberta até o cozido estar pronto",
        sugestoes57: "Para almoçar o cozido recomendamos os restaurantes Tony´s ou Miroma",
        sugestoes58: "Poça da Dona Beija",
        sugestoes59: "3€ a entrada, água a 38-40ºC. A água está carregada de minerais essenciais. Balneários disponíveis, com água quente e fria",
        sugestoes60: "Parque Terra Nostra (o bilhete custa 6€). Logo à entrada tem um tanque de água termal onde se pode tomar banho. A água é quente e alaranjada (não se vê o fundo) e está a 35 / 40 graus, o provoca uma sensação de relaxamento maravilhosa. A água está carregada de minerais essenciais. Existem outras duas piscinas pequenas e o parque tem balneários disponíveis",
        sugestoes61: "Passar pelo Miradouro Salto do Cavalo, a 760 metros de altitude, onde se vê uma vasta vista sobre o vale da Povoação e as suas sete lombas. Ao fundo, até ao horizonte, surge o mar",
        sugestoes62: "Ir até à Praia da Ribeira Quente, onde a existência de nascentes hidrotermais submarinas tornam a água do mar quente<",
        sugestoes63: "Regressar pela costa norte",
        sugestoes64: "Ilhéu de Vila Franca",
        sugestoes65: "agora aparentemente pode-se comprar os bilhetes online, anteriormente tínhamos que ir super cedo para lá porque só vendem 400 bilhetes por dia. Podem ir passar a manhã ou a tarde no ilhéu. Em maré baixa tem uma praia pequenita, senão ficam nas zonas de rocha. Tomar banho no ilhéu é uma experiência muito gira. Recomendamos levar sapatos de plástico para andar nas rochas já que o fundo do ilhéu é rocha e pode ser desconfortável",
        sugestoes66: "Fábrica do Morgado – queijadas da Vila Franca",
        sugestoes67: "Praias de Água d’Alto",
        sugestoes68: "Cascata do Segredo",
        sugestoes69: "Miradouro do Pisão",
        sugestoes70: "Caloura e praia da Caloura (come-se bem no",
        sugestoes71: "Outras sugestões",
        sugestoes72: "A costa Norte por norma é sempre mais bonita que a costa Sul (miradouros, viagem, etc.), por isso se estiver um dia bonito aconselhamos dar prioridade",
        sugestoes73: "(recomendamos o absurdo - cerveja e camarões, e o gelado de canela)",
        sugestoes74: "(tomar um copo)",
        sugestoes75: "(come-se muito bem e não é caro)",
        sugestoes76: "Estufas de Ananás",
        sugestoes77: "(o que vale a pena são as saladas e os gelados! Os crepes também são bons)",
        sugestoes78: "Restaurante o Galego",
        sugestoes79: "(o melhor bife)",
        sugestoes80: "Restaurante da Associação Agrícola",
        sugestoes81: "(sinceramente nunca lá fomos, mas tem muita reputação)",
    }
});