import LocalizedStrings from 'react-localization';

export default new LocalizedStrings({
    pt: {
        footer: "Todos os direitos reservados.",
        menu1: "Página Principal",
        menu2: "A Nossa História",
        menu3: "O Pedido",
        menu4: "Gang Madrinhal",
        menu5: "Padrinho",
        menu6: "O Casamento",
        menu7: "Fornecedores",
        menu8: "Viajar Para Sāo Miguel",
        menu9: "Estadia",
        menu10: "Sugestões dos Noivos",
        menu11: "Fotos",
        menu12: "Contactos",
        menu13: "RSVP",
        homeText: "Bem-vindo(s) à página oficial do nosso casamento.",
        brevemente: "Disponível Brevemente!",
        notfound: "Página não encontrada",
        oCasamento1: "O Casamento",
        oCasamento2: "Data",
        oCasamento3: "Hora",
        oCasamento4: "Local",
        contactos1: "Contactos",
        contactos2: "Qualquer dúvida contactem-nos através do email",
        contactos3: "ou enviem-nos uma mensagem para o WhatsApp (número inglês; os número portugueses não estão activos) ou Messenger.",
        fotos1: "Secção disponível após o casamento!",
        viajar1: "Lisboa",
        estadia1: "Estadia",
        estadia2: "Neste momento há muita oferta de estadia em São Miguel. Se vêm de férias por alguns dias recomendamos um airbnb ou hostel no centro de Ponta Delgada, mas se quiserem ficar connosco no local do casamento, por favor vejam a informação abaixo relativa ao Convento de São Francisco. Deixamos outras sugestões abaixo, mas apelamos ao vosso sentido crítico pois como podem imaginar nós não costumamos alugar espaço para ficarmos.",
        estadia3: "local do casamento",
        estadia4: "Enviar email para",
        estadia5: "para marcações com 10% de desconto relativamente ao preço no",
        estadia6: "Nunca ficámos neste hotel, mas já lá jantámos 2x (noite de sushi) e visitámos o espaço. O staff é super simpático e o jardim é fantástico. Recomendamos darem uma vista de olhos.",
        estadia7: "Qualquer dúvida em que possamos ajudar ou dar uma opinião falem connosco.",
        estadia8: "Independentemente de onde fiquem, recomendamos alugar carro (a nosso ver é mesmo obrigatório para poderem ver a ilha). Algumas sugestões (baseadas em críticas no Google), mas novamente apelando ao vosso sentido crítico porque não costumamos alugar carro na ilha:",
        pedido1: "O Pedido",
        pedido2: "Data: 3 de Março de 2017",
        pedido3: "Local: Praia do Pópulo, São Miguel (Açores)",
        pedido4: "Foi no ano de 2006 (a 29 de Julho de 2006 mais precisamente), primeiro ano de namoro, que o João fez um piquenique na praia para a Isabel (infelizmente não há fotos desse evento). Essa surpresa contou com cúmplices, os pais do João, que vendaram e levaram a Isabel ao local, que não fazia ideia do que a esperava. Apesar do esforço do João, nesse dia ele não teve muita sorte (não fosse o João) porque teve que acarinhar uma Isabel com febre (a Isabel tem frequentemente uma pontaria enorme em ficar doente em alturas muito pouco convenientes).",
        pedido5: "Em 2017 o João resolveu repetir a surpresa, desta feita para aproveitar a fazer o pedido de casamento. Obviamente que a Isabel suspeitou, mas 1) já tinham surgido outras oportunidades, 2) o João estava super calmo, e 3) passou-se praticamente 1h até que o João resolveu fazer magia. E ainda conseguiu enganar a Isabel a levantar-se para se poder ajoelhar e pedir a Isabel em casamento. \"Queres continuar a fazer-me o homem mais feliz do mundo?\".  Foi muito bonito. Houve uma pequena lágrima (da Isabel. claro), beijo, abraço e muitos sorrisos. E, claro, algumas fotos. Por isso aqui fica. Esperemos que tenham gostado de partilhar um pouco do momento connosco. :)",
        fornecedores1: "Fornecedores",
        fornecedores2: "Espaço",
        fornecedores3: "Fotografia",
        fornecedores4: "Noiva",
        fornecedores5: "Noivo",
        fornecedoresBrevemente: "Informaçāo brevemente disponível!",
    },
    en: {
        footer: "All rights reserved.",
        menu1: "Home",
        menu2: "Our Story",
        menu3: "The Proposal",
        menu4: "Bridal Gang",
        menu5: "Best Man",
        menu6: "The Wedding",
        menu7: "Suppliers",
        menu8: "Travelling to Sāo Miguel",
        menu9: "Accommodation",
        menu10: "Suggestions",
        menu11: "Photos",
        menu12: "Contacts",
        menu13: "RSVP",
        homeText: "Welcome to our wedding's official web site.",
        brevemente: "Page available soon.",
        notfound: "Page not found",
        oCasamento1: "The Wedding",
        oCasamento2: "Date",
        oCasamento3: "Time",
        oCasamento4: "Location",
        contactos1: "Contacts",
        contactos2: "If you have any questions just send an email to",
        contactos3: "or send us a message on WhatsApp or Messenger.",
        fotos1: "Available after the wedding!",
        viajar1: "Lisbon",
        estadia1: "Accommodation",
        estadia2: "At the moment there is a lot of offering in Sāo Miguel island. If you are taking a few days of holidays, we recommend booking an AirBNB or hostel in the centre of Ponta Delgada, although if you are looking to stay closer to the wedding venue please see the below details regarding the venue. We will also add a few suggestions below, but bear in mind we don't usually book any of these places ourselves.",
        estadia3: "wedding venue",
        estadia4: "Send an email to",
        estadia5: "for 10% discount in bookings compared to the price at",
        estadia6: "We have never booked this hotel, but have had a sushi dinner and visited the venue. Staff is very polite and the garden is fantastic. We recommend having a look at this one.",
        estadia7: "For any questions, opinions or anything else we could help with please contact us.",
        estadia8: "Regardless of where you will stay we definitely recommend renting a car (in our opinion it is pretty much mandatory to be able to see the island properly). Some suggestions based on a quick Google search, but again make sure to do a bit of your own research because we do not typically rent a car in the island:",
        pedido1: "The Proposal",
        pedido2: "Date: March 3rd 2017",
        pedido3: "Location: Pópulo beach, São Miguel (Azores)",
        pedido4: "In the year of 2006 (more specifically July 29th 2006), during the first year of being a couple, João planned a picnic at the beach for Isabel (Unfortunately there are no pictures of this event). This surprise had a few accomplices, namely João's parents, who blindfolded and took Isabel (who had no idea what was waiting for her) to the location. Unfortunately even with all of João's effort, he wasn't very lucky on that day (typical João) because he had to cuddle with a feverish Isabel (she is prone to becoming ill at the most convenient of times).",
        pedido5: "In 2017 João decided to repeat the surprise, but this time to actually propose. Obviously Isabel suspected but 1) there were a few other opportunities, 2) João was way too calm, e 3) one hour passed until João decided to do his magic. He was still able to trick Isabel into standing so he could kneel down to propose. \"Will you make me the happiest man in the world?\". It was very touching. A small tear fell (obviously Isabel's), kiss, hugs and plenty of smiles. And obviously some photos taken. And that is it. We hope you enjoyed this little story we shared with you. :)",
        fornecedores1: "Suppliers",
        fornecedores2: "Venue",
        fornecedores3: "Photography",
        fornecedores4: "Bride",
        fornecedores5: "Groom",
        fornecedoresBrevemente: "Information available soon!",
    }
});